#!/usr/bin/env bash

nv_cmd_default() {
    local env_name=$1
    if [ "$env_name" != "" ]; then
        echo $env_name > ./.envirius
        return
    fi

    local env_name=`nv current`
    if [ "$env_name" != "" ]; then
        echo $env_name > ./.envirius
        return
    fi

    nv_cmd_help
}

nv_cmd_desc() {
    echo "Mark current directory for environment auto activating"
}

nv_cmd_help() {
    nv_show_usage "[<env-name>]"
    nv_show_desc "$(nv_cmd_desc)"
    echo "    If environment's name is not entered then used current"
    echo "    (active) environment. If environment is not activated"
    echo "    then environment's name is required."
}

# /* vim: set filetype=sh : */
