#!/usr/bin/env bash

nv_cmd_default() {
    # deactivate previusly activated environment
    if [ "$NV_USED_ENV" != "" ]; then
        echo $NV_USED_ENV
    fi
}

nv_cmd_desc() {
    echo "Output current environment's name"
}

nv_cmd_help() {
    nv_show_usage
    nv_show_desc "$(nv_cmd_desc)"
}

# /* vim: set filetype=sh : */
