#!/usr/bin/env bash

nv_cmd_default() {
    # lists all files in the commands directory
    # except hidden and common file
    local commands_full_path=$(nv_get_command_full_path)
    for cmd in $(find $commands_full_path \
                    -type f \
                    -not -iname ".*" | sort)
    do
        # source each command
        . $cmd
        # display it's filename only & description for it
        echo "  `nv_rpad $(nv_get_filename $cmd) 15` $(nv_cmd_desc)"
    done
}

nv_cmd_desc() {
    echo "List available commands"
}

nv_cmd_help() {
    nv_show_usage
    nv_show_desc "$(nv_cmd_desc)"
}

# /* vim: set filetype=sh : */
