#!/usr/bin/env bash

nv_cmd_default() {
    local env_name_src=$1
    local env_name_dst=$2

    # envs are mandotory
    if [ "$env_name_src" = "" ]; then
        echo "Please, enter a name for a source environment"
        echo ""
        nv_cmd_help
        return
    fi
    if [ "$env_name_dst" = "" ]; then
        echo "Please, enter a name for a destination environment"
        echo ""
        nv_cmd_help
        return
    fi

    # full paths
    local env_name_src_full=$(nv_get_env_full_path $env_name_src)
    local env_name_dst_full=$(nv_get_env_full_path $env_name_dst)

    # sourc env should exists
    if [ ! -d "$env_name_src_full" ]; then
        echo "Source directory does not exist ($env_name_src)."
        return
    fi

    # target env should not exists
    if [ -d "$env_name_dst_full" ]; then
        echo "Target directory already exists ($env_name_dst)."
        return
    fi

    mv "$env_name_src_full" "$env_name_dst_full"
}

nv_cmd_desc() {
    echo "Move (rename) environment"
}

nv_cmd_help() {
    nv_show_usage "<env-name-src> <env-name-dst>"
    nv_show_desc "$(nv_cmd_desc)"
}

# /* vim: set filetype=sh : */
