#!/usr/bin/env bash

nv_cmd_default() {
    env_name=""

    # try to find --all option
    for opt in "$@"
    do
    case $opt in
        --all)
            env_name_full=$(nv_get_env_full_path)
            rm -rf $env_name_full/*
            return
    esac
    done

    # try to find env name
    for env_name in "$@"
    do
        env_name_full=$(nv_get_env_full_path $env_name)
        if [ -d "$env_name_full" ]; then
            rm -rf $env_name_full
            echo "Environment `nv_bold $env_name` was deleted."
        fi
    done
}

nv_cmd_desc() {
    echo "Delete environment"
}

nv_cmd_help() {
    nv_show_usage "[options] <env-name> [env-name, ...]"
    nv_show_desc "$(nv_cmd_desc)"
    echo ""
    echo "Options:"
    echo "  --all   Delete all environments"
}

# /* vim: set filetype=sh : */
