#!/bin/sh

# Columns count in the version's grid
plug_list_versions_columns_count=6

# Column's width in characters in the version's grid
plug_list_versions_columns_size=10

ERL_MIRROR="http://www.erlang.org/download/"

# Output lists of versions
plug_list_versions() {
    local versions1=$(curl -s $ERL_MIRROR | \
        egrep -o '\/download\/otp_src_(R1[-0-9A-Za-z_]+)\.tar\.gz' | \
        egrep -o 'otp_src_R1[-0-9A-Za-z]+' | \
        egrep -o 'R1[-0-9A-Za-z]+')
    local versions2=$(curl -s $ERL_MIRROR | \
        egrep -o "otp_src_[0-9]+\.[0-9]+(-rc[0-9]+)*\.tar\.gz" | \
        egrep -o "[0-9]+\.[0-9]+(-rc[0-9]+)*")
    echo "$versions1 $versions2"
}

# Return full url for tarball for download
# and future installation
#
# Input:
#   $1 — version for installation
plug_get_url_for_download() {
    version=$1
    echo "$ERL_MIRROR/otp_src_${version}.tar.gz"
}
