#!/bin/sh

# Output lists of versions
plug_list_versions() {
    local versions=$(curl -s "https://code.google.com/p/go/downloads/list?can=1&q=Linux+386" | \
        egrep -o "\/go[0-9]+\.[0-9]+(\.[0-9]+|rc[0-9]{1})\.linux-386.tar.gz" | \
        sort | uniq | egrep -o "[0-9]+\.[0-9]+(\.[0-9]+|rc[0-9]{1})")
    echo $versions
}

plug_install() {
    local plugin_name=$1
    local version=$2
    local env_name_full=$3
    local arch=$(get_system_arch)

    local remote_tarball="https://go.googlecode.com/files/go${version}.linux-${arch}.tar.gz"
    local tarball=$(download_file "$remote_tarball" "${plugin_name}-${version}.tar.gz")
    # execute in subshell
    (
        local src_path=$(get_cache_full_path "$plugin_name-$version-src")

        # unpacking (if need)
        if [ ! -d "$src_path" ]; then
            mkdir -p "$src_path"
            tar -xzf "$tarball" -C "$src_path"
        fi

        # copy all bins into new environment
        cp -r "$src_path"/* $env_name_full
        ln -s "$env_name_full/go/bin" "$env_name_full/bin"

        # add activate script
        local activate_path="$env_name_full/bin/activate-go"
        echo "export NV_OLD_GOROOT=\$GOROOT" > "$activate_path"
        echo "export NV_OLD_GOPATH=\$GOPATH" >> "$activate_path"
        echo "export GOROOT=$env_name_full/go" >> "$activate_path"
        echo "export GOPATH=$env_name_full/gocode" >> "$activate_path"
        echo "export PATH=\$GOPATH/bin:\$PATH" >> "$activate_path"
        chmod a+x "$activate_path"

        local deactivate_path="$env_name_full/bin/deactivate-go"
        echo "export GOROOT=\$NV_OLD_GOROOT" > "$deactivate_path"
        echo "export GOPATH=\$NV_OLD_GOPATH" >> "$deactivate_path"
        chmod a+x "$deactivate_path"
    )
}
