#!/bin/sh

# Output lists of versions
plug_list_versions() {
    local versions=$(curl -s "https://code.google.com/p/go/downloads/list?can=1&q=Linux+386" | \
        egrep -o "\/go[0-9]+\.[0-9]+(\.[0-9]+|rc[0-9]{1})\.linux-386.tar.gz" | \
        sort | uniq | egrep -o "[0-9]+\.[0-9]+(\.[0-9]+|rc[0-9]{1})")
    echo $versions
}

plug_install() {
    local plugin_name=$1
    local version=$2
    local env_name_full=$3
    local arch=$(nv_get_system_arch "386" "amd64")

    local remote_tarball="https://go.googlecode.com/files/go${version}.linux-${arch}.tar.gz"
    local tarball=$(nv_download_file "$remote_tarball" "${plugin_name}-${version}.tar.gz")
    # execute in subshell
    (
        local src_path=$(nv_get_cache_full_path "$plugin_name-$version-src")

        # unpacking (if need)
        if [ ! -d "$src_path" ]; then
            mkdir -p "$src_path"
            tar -xzf "$tarball" -C "$src_path"
        fi

        # copy /go directory into env
        cp -r "$src_path"/* $env_name_full
        # create environments /bin directory
        mkdir -p "$env_name_full/bin"
        # create symlinks on each executable file into main /bin
        (
            cd "$env_name_full/go/bin"
            ln -s `find . -executable -type f -printf '../go/bin/%f\n'` "$env_name_full/bin"
        )

        # add activate script
        local activate_path="$env_name_full/bin/activate-go"
        echo "NV_ENV=\$(nv current)" > "$activate_path"
        echo "NV_ENV_PATH=\$(nv_get_env_full_path \$NV_ENV)" >> "$activate_path"
        echo "export NV_OLD_GOROOT=\$GOROOT" >> "$activate_path"
        echo "export NV_OLD_GOPATH=\$GOPATH" >> "$activate_path"
        echo "export GOROOT=\$NV_ENV_PATH/go" >> "$activate_path"
        echo "export GOPATH=\$NV_ENV_PATH/gocode" >> "$activate_path"
        echo "export PATH=\$GOPATH/bin:\$PATH" >> "$activate_path"
        chmod a+x "$activate_path"

        local deactivate_path="$env_name_full/bin/deactivate-go"
        echo "export GOROOT=\$NV_OLD_GOROOT" > "$deactivate_path"
        echo "export GOPATH=\$NV_OLD_GOPATH" >> "$deactivate_path"
        chmod a+x "$deactivate_path"
    )
}
