#!/bin/sh

NODE_MIRROR="http://nodejs.org/dist"

# Output lists of versions
plug_list_versions() {
    local versions=$(curl -s "$NODE_MIRROR/" | \
                grep -v "node-" | \
                egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | \
                sort -u -k 1,1n -k 2,2n -k 3,3n -t .)
    echo $versions
}

# Return full url for tarball for download
# and future installation
#
# Input:
#   $1 — version for installation
plug_url_for_download() {
    local version=$1
    echo "$NODE_MIRROR/v${version}/node-v${version}.tar.gz"
}
