#!/usr/bin/env bash

# Output lists of versions
plug_list_versions() {
    echo $(curl -s http://php.net/downloads.php \
                   http://php.net/releases/ | \
            egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' | sed 's/.tar.gz//' | \
            sort | uniq | sort)
}

# Download tarball
plug_download() {
    local plugin_name=$1
    local version=$2

    local tarball_url="http://us3.php.net/get/php-${version}.tar.gz/from/this/mirror"
    local tarball_cache="${plugin_name}-${version}.tar.gz"
    local tarball=$(nv_download_file "$tarball_url" "$tarball_cache")

    echo "$tarball"
}
