#!/bin/sh

PY_MIRROR="https://www.python.org"

# Output lists of versions
plug_list_versions() {
    local versions=$(curl -s "$PY_MIRROR/downloads/" | grep "release-number" | \
                grep -E -o '\s[0-9]+\.[0-9]+\.[0-9]+')
    echo $versions
}

# Return full url for tarball for download
# and future installation
#
# Input:
#   $1 — version for installation
plug_url_for_download() {
    local version=$1
    echo "$PY_MIRROR/ftp/python/$version/Python-$version.tgz"
}
