#!/usr/bin/env bash

# Output lists of versions
plug_list_versions() {
    echo $(curl -s https://github.com/rust-lang/rust/wiki/Doc-releases | \
        egrep 'static.rust-lang.org\/dist\/rust-[0-9]+\.[0-9]+\.tar\.gz' | \
        egrep -o '[0-9]+\.[0-9]+' | uniq | sort --version-sort)
}

# Return full url for tarball
plug_url_for_download() {
    local version=$1
    local arch=$(nv_get_system_arch "i686" "x86_64")
    local system=$(nv_get_system "unknown-linux-gnu" "apple-darwin")
    echo "http://static.rust-lang.org/dist/rust-${version}-${arch}-${system}.tar.gz"
}

# Like we build
plug_build() {
    local src_path=$1
    local build_path=$2
    cp -r "$src_path"/*/* "$build_path"
}
