#!/usr/bin/env bash

# Output lists of versions
plug_list_versions() {
    echo $(curl -s https://github.com/rust-lang/rust/wiki/Doc-releases | \
        egrep 'static.rust-lang.org\/dist\/rust-[0-9]+\.[0-9]+(\.[0-9]+)*\.tar\.gz' | \
        egrep -o '[0-9]+\.[0-9]+(\.[0-9]+)*' | uniq | sort --version-sort)
    echo "nightly"
}

# Return full url for tarball for download
plug_url_for_download() {
    local version=$1
    echo "http://static.rust-lang.org/dist/rust-${version}.tar.gz"
}

# create activate/deactivate scripts
plug_post_install_actions() {
    local env_name=$1
    local env_name_full=$2

    # add activate script
    local activate_path="$env_name_full/bin/activate-rust"
    echo "NV_ENV=\$(nv current)" > "$activate_path"
    echo "NV_ENV_PATH=\$(nv_get_env_full_path \$NV_ENV)" >> "$activate_path"
    echo "export OLD_LD_LIBRARY_PATH=\$LD_LIBRARY_PATH" >> $activate_path
    echo "export LD_LIBRARY_PATH=\$NV_ENV_PATH/lib" >> $activate_path
    chmod a+x "$activate_path"

    local deactivate_path="$env_name_full/bin/deactivate-rust"
    echo "export LD_LIBRARY_PATH=\$OLD_LD_LIBRARY_PATH" > "$deactivate_path"
    chmod a+x "$deactivate_path"
}
