#!/usr/bin/env bash

# Output lists of versions
plug_list_versions() {
    echo $(curl -s https://github.com/mozilla/rust/wiki/Doc-releases | \
        egrep 'static.rust-lang.org\/dist\/rust-[0-9]+\.[0-9]+\.tar\.gz' | \
        egrep -o '[0-9]+\.[0-9]+' | uniq | sort --version-sort)
}

# Return full url for tarball for download
plug_url_for_download() {
    local version=$1
    echo "http://static.rust-lang.org/dist/rust-${version}.tar.gz"
}
