#!/bin/sh

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
    set -x
fi

# usefull directories
if [ "$MEM_PATH" = "" ]; then
    export MEM_PATH=$HOME/.mem
fi
export MEM_COMMANDS_DIR=$MEM_PATH/mem-commands

if [ "$MEM_HOME" = "" ]; then
    export MEM_HOME=$HOME/.mem
fi
export MEM_CACHE_DIR=$MEM_HOME/cache
export MEM_ENVS_DIR=$MEM_HOME/envs

# load common functions
. $MEM_COMMANDS_DIR/common


mem_usage() {
    mem version
    show_usage "<subcommand>"
    echo
    echo "Subcommands:"
    mem commands
    echo
    echo "Try '$(get_cmd_name) <subcommand> --help' for details."
    echo "For more information, see: https://github.com/ekalinin/$(get_cmd_name)"
}


mem() {
    mkdir -p $MEM_ENVS_DIR
    mkdir -p $MEM_CACHE_DIR

    # get command from first command line arg
    SUBCOMMAND="$1"; shift

    # show help if command is empty
    if [ "$SUBCOMMAND" = "" ]; then
        mem_usage
        return
    # show help if command not exists
    elif [ ! -e "$MEM_COMMANDS_DIR/$SUBCOMMAND" ]; then
        mem_usage
        return
    fi

    # run command
    . "$MEM_COMMANDS_DIR/$SUBCOMMAND"

    SUBACTION="default"
    if [ "$1" = "--help" ]; then
        SUBACTION="help";
    fi

    # run subaction
    mem_cmd_$SUBACTION "$@"
}


# /* vim: set filetype=sh : */
