#!/bin/sh

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
    set -x
fi

# path to then soure code
if [ "$NV_PATH" = "" ]; then
    export NV_PATH=$HOME/.envirius
fi

# path to the cache/environment/etc
if [ "$NV_HOME" = "" ]; then
    export NV_HOME=$HOME/.envirius
fi

# load common functions
. $NV_PATH/nv_common


nv_usage() {
    nv version
    nv_show_usage "<subcommand>"
    echo
    echo "Subcommands:"
    nv ls-commands
    echo
    echo "Try '$(nv_cmd_name) <subcommand> --help' for details."
    echo "For more information, see: https://github.com/ekalinin/envirius"
}


nv() {
    mkdir -p $(nv_get_env_full_path)
    mkdir -p $(nv_get_cache_full_path)

    # get command from first command line arg
    SUBCOMMAND="$1"; shift
    local command_full_path=$(nv_get_command_full_path $SUBCOMMAND)

    # show help if command is empty
    if [ "$SUBCOMMAND" = "" ]; then
        nv_usage
        return
    # show help if command not exists
    elif [ ! -e "$command_full_path" ]; then
        nv_usage
        return
    fi

    # run command
    . "$command_full_path"

    SUBACTION="default"
    if [ "$1" = "--help" ]; then
        SUBACTION="help";
    fi

    # run subaction
    nv_cmd_$SUBACTION "$@"
    unset SUBCOMMAND
    unset SUBACTION
}


_nv() {

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cmd="${COMP_WORDS[1]}"

    if [ $COMP_CWORD == 1 ] ; then
        cmd_list=$(nv ls-commands | cut -d ' ' -f 3)
        COMPREPLY=( $(compgen -W "${cmd_list}" -- ${cur}) )
        return 0
    fi

    # ls-versions|mk --<plugin>[ --<plugin>]
    if [[ ${cur} == -* && ("${cmd}" == "ls-versions" || "${cmd}" == "mk") ]] ; then
        local opt_plugins=$(nv ls-plugins | awk '{print "--"$1}')
        local opt_others=$(nv ${cmd} --help | grep "  \-\-" | cut -d ' ' -f 3)
        COMPREPLY=( $(compgen -W "${opt_plugins} ${opt_others}" -- ${cur}) )
        return 0
    fi

    # rm <environment-name>[ <environment-name>]
    if [[ "${cmd}" == "rm" ]] ; then
        local env_list=$(nv ls --no-meta | tail -n+2)
        COMPREPLY=( $(compgen -W "${env_list}" -- ${cur}) )
        return 0
    fi

    # any option from command's help output
    if [[ ${cur} == -* ]] ; then
        local command_opts=$(nv $prev --help | grep "\-\-" | cut -d ' ' -f 3)
        COMPREPLY=( $(compgen -W "${command_opts}" -- ${cur}) )
        return 0
    fi

    # on|activate|use|do <environment-name>
    if [[ "${prev}" == "on" || "${prev}" == "activate" || "${prev}" == "use" || "${prev}" == "do" ]] ; then
        local env_list=$(nv ls --no-meta | tail -n+2)
        COMPREPLY=( $(compgen -W "${env_list}" -- ${cur}) )
        return 0
    fi
}

complete -F _nv nv

# /* vim: set filetype=sh : */
