#!/bin/sh

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
    set -x
fi

# path to then soure code
if [ "$NV_PATH" = "" ]; then
    export NV_PATH=$HOME/.envirius
fi

# path to the cache/environment/etc
if [ "$NV_HOME" = "" ]; then
    export NV_HOME=$HOME/.envirius
fi

# load common functions
. $NV_PATH/nv_common


nv_usage() {
    nv version
    show_usage "<subcommand>"
    echo
    echo "Subcommands:"
    nv commands
    echo
    echo "Try '$(get_cmd_name) <subcommand> --help' for details."
    echo "For more information, see: https://github.com/ekalinin/$(get_cmd_name)"
}


nv() {
    mkdir -p $(get_env_full_path)
    mkdir -p $(get_cache_full_path)

    # get command from first command line arg
    SUBCOMMAND="$1"; shift
    local command_full_path=$(get_command_full_path $SUBCOMMAND)

    # show help if command is empty
    if [ "$SUBCOMMAND" = "" ]; then
        nv_usage
        return
    # show help if command not exists
    elif [ ! -e "$command_full_path" ]; then
        nv_usage
        return
    fi

    # run command
    . "$command_full_path"

    SUBACTION="default"
    if [ "$1" = "--help" ]; then
        SUBACTION="help";
    fi

    # run subaction
    nv_cmd_$SUBACTION "$@"
    unset SUBCOMMAND
    unset SUBACTION
}


# /* vim: set filetype=sh : */
