#!/bin/sh

# Output lists of versions
plug_list_versions() {
    PY_MIRROR="http://www.python.org/ftp/python/"
    versions=$(curl -s $PY_MIRROR | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | \
                sort | uniq)
    echo $versions
}

plug_install() {
    echo " * installing $1 ..."
}
